// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyqqlqtwpixbbfflsztc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cXFscXR3cGl4YmJmZmxzenRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzE5MzAsImV4cCI6MjA2ODk0NzkzMH0.nurEEckMYSqT3N_ZXv-vjG4jOFVvb5qHzQSjg-139wc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});